# @file SBCL-test.yml
---
name: SBCL-Tests
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Update apt package list
        run: sudo apt update

      - name: Download sbcl
        run: sudo apt install -y sbcl

      - name: Download quicklisp
        run: curl -o quicklisp.lisp 'https://beta.quicklisp.org/quicklisp.lisp'

      - name: Install quicklisp
        run: |
          sbcl --noinform --non-interactive --load quicklisp.lisp --eval "(quicklisp-quickstart:install :path \"$GITHUB_WORKSPACE/quicklisp/\")"
          sbcl --noinform --non-interactive --load "$GITHUB_WORKSPACE/quicklisp/setup.lisp" --eval '(ql-util:without-prompting (ql:add-to-init-file))'

      - name: Download repo
        uses: actions/checkout@v2
        with:
          path: quicklisp/local-projects/cl-protobufs

      - name: Add cl-protobufs/protoc to path
        run: echo "::add-path:$GITHUB_WORKSPACE/quicklisp/local-projects/cl-protobufs/protoc/"

      - name: Download and install protobuf
        run: sudo apt install -y protobuf-compiler libprotobuf-dev libprotoc-dev libabsl-dev

      - name: Install protoc plug-in
        run: |
          cd $GITHUB_WORKSPACE/quicklisp/local-projects/cl-protobufs/protoc &&
          PROTOC_ROOT=/usr make

      - name: Load and run tests
        run: |
          export PATH="$PATH:$GITHUB_WORKSPACE/quicklisp/local-projects/cl-protobufs/protoc/"
          sbcl --noinform --non-interactive --eval '(ql:quickload :clunit2)' --eval '(ql:quickload :trivial-benchmark)' --eval '(ql:quickload :cl-base64)' --eval '(ql:quickload :local-time)' --eval '(ql:quickload :babel)' --eval '(setf clunit:*clunit-report-format* :tap)' --eval '(ql:quickload :cl-protobufs)' --eval '(asdf:test-system :cl-protobufs)' >> report
          test -f report
          cat report
          ! grep -q "not ok" report
          grep -q "ok" report
